### ISSUE TITLE
include FortiAP statistics

### ISSUE THREAD

**Issue by mbdraks** [mbdraks/fortinet-zabbix#28]
Contributed by Guilherme Silva (www.focaldata.com.br)

Add of discovery related to FortiAPs
[Template Net Fortinet FortiGate SNMPv2 - FAP.xml.zip](https://github.com/barbosm/fortinet-zabbix/files/4974237/Template.Net.Fortinet.FortiGate.SNMPv2.-.FAP.xml.zip)

**Comment by barbosm** [comment]
This update will include the following OIDs

1.3.6.1.4.1.12356.101.14.4.3.1.3
1.3.6.1.4.1.12356.101.14.4.4.1.1
1.3.6.1.4.1.12356.101.14.4.4.1.3
1.3.6.1.4.1.12356.101.14.4.4.1.5
1.3.6.1.4.1.12356.101.14.4.4.1.6
1.3.6.1.4.1.12356.101.14.4.4.1.7
1.3.6.1.4.1.12356.101.14.4.4.1.10
1.3.6.1.4.1.12356.101.14.4.4.1.11
1.3.6.1.4.1.12356.101.14.4.4.1.12
1.3.6.1.4.1.12356.101.14.4.4.1.14
1.3.6.1.4.1.12356.101.14.4.4.1.17
1.3.6.1.4.1.12356.101.14.4.4.1.20
1.3.6.1.4.1.12356.101.14.4.4.1.21

**Comment by mbdraks** [comment]
Closed by #31
