### ISSUE TITLE
Dificuldades WIFI

### ISSUE THREAD

**Issue by andreynobre** [mbdraks/fortinet-zabbix#32]
Olá pessoal, não estou conseguindo fazer a soma de todos os clientes conectados no wifi... no zabbix não funciona e no grafana não está mostrando o numero correto.

No zabbix: last(fgWcWtpSessionWtpByteRxCount.rate.[{#SNMPVALUE}])

No grafana: /Connected*/

nenhuma forma deu certo.

**Comment by mbdraks** [comment]
@andreynobre 

O valor de clientes conectados por AP está correto?

**Comment by andreynobre** [comment]
@mbdraks 

Está sim... tenho 11 aps, individualmente aparece corretamente, só não estou conseguindo fazer a soma de todos.

**Comment by mbdraks** [comment]
Tente criar um item do tipo 'Calculated', coloque uma key qualquer como por exemplo 'fgWcWtpSessionWtpStationCountTotal' e na formula use algo parecido com o seguinte:

last("fgWcWtpSessionWtpStationCount.[SN_AP1]")+last("fgWcWtpSessionWtpStationCount.[SN_AP2]")

Onde SN_AP1 e SN_AP2 são os seriais dos APs já descobertos (esses items já devem existir associados ao host).

**Comment by andreynobre** [comment]
@mbdraks vou criar aqui, e tentar fazer isso, quando eu terminar, digo aqui o resultado. obrigado pela ajuda

**Comment by mbdraks** [comment]
Pode conferir também qual o valor da métrica fgWcInfoStationCount?

Supostamente ela deveria dar o valor de clientes conectados total por controladora. Não sei se seu caso é de vários APs na mesma controller ou não, mas vale conferir.

**Comment by andreynobre** [comment]
@mbdraks são 11 APs num fortigate 200E.. como disse, individualmente mostra tudo certinho... só não consegui fazer a soma dos 11.

**Comment by mbdraks** [comment]
Solution provided on https://github.com/mbdraks/fortinet-zabbix/issues/32#issuecomment-733852047.
