### ISSUE TITLE
refactor template for zabbix 5.2

### ISSUE THREAD

**Issue by mbdraks** [mbdraks/fortinet-zabbix#35]
format changed a lot and probably the current XML template will not load properly on newer zabbix versions, need to refactor

**Comment by WB-Isaiah** [comment]
Hello, you are correct, the item does not load in 5.2 and it outputs this error "Cannot import template "Template Net Fortinet FortiGate SNMPv2", linked templates "Template Module EtherLike-MIB SNMPv2, Template Module Generic SNMPv2, Template Module Interfaces SNMPv2" do not exist."

**Comment by mbdraks** [comment]
Just released v2.0.0 which fixes this. Zabbix 5.2 is now supported.

https://github.com/mbdraks/fortinet-zabbix/releases/tag/v2.0.0
