### ISSUE TITLE
Import template fail

### ISSUE THREAD

**Issue by hzome** [mbdraks/fortinet-zabbix#36]
Trying to import to a Zabbix appliance 4.4 and got the error bellow:
No permissions to referred object or it does not exist! [conf.import.php:174 → CFrontendApiWrapper->import() → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → call_user_func_array() → CConfiguration->import() → CConfigurationImport->import() → CConfigurationImport->processGraphs() → CGraphGeneral->update() → CApiService::exception() in include/classes/api/services/CGraphGeneral.php:64]

<img width="1435" alt="WechatIMG115" src="https://user-images.githubusercontent.com/1510628/107114493-14a03880-68a1-11eb-9ae5-874badbfd879.png">

**Comment by mbdraks** [comment]
Zabbix 4.4 is supported until v1.5 of the template, available here: https://github.com/mbdraks/fortinet-zabbix/releases/tag/v1.5.0

**Comment by mbdraks** [comment]
Closing as solved, the legacy template is available in the URL sent in my previous post.
