### ISSUE TITLE
Import template error

### ISSUE THREAD

**Issue by jonathanwtf** [mbdraks/fortinet-zabbix#37]
I'm trying to import the template in zabbix 5.0.8 and no version of the template is working, all versions return the same error:

![image](https://user-images.githubusercontent.com/79288080/108432973-fed92e80-7223-11eb-9df0-78c968105642.png)

**Comment by jonathanwtf** [comment]
resolved

**Comment by mbdraks** [comment]
@jonathanwtf 

Did you had to change something on the template to fix it?
