### ISSUE TITLE
Support for LTS Zabbix (5.0.x)

### ISSUE THREAD

**Issue by samip5** [mbdraks/fortinet-zabbix#44]
Could that template be also be made for the LTS version of Zabbix aka 5.0.x? It requires the templates to be imported as xml and yaml is not supported.

**Comment by mbdraks** [comment]
I publish the XML version of the current template on https://share.zabbix.com/network_devices/fortinet-fortigate 

Can you please confirm if that version works on 5.0? 

If it does I can change from YAML to XML in the repo too in order to only support a single version, considering that 5.2 also support XML.

**Comment by samip5** [comment]
> I publish the XML version of the current template on https://share.zabbix.com/network_devices/fortinet-fortigate
> 
> Can you please confirm if that version works on 5.0?
> 
> If it does I can change from YAML to XML in the repo too in order to only support a single version, considering that 5.2 also support XML.

It doesn't.

![image](https://user-images.githubusercontent.com/1703002/119085552-a07f4000-ba0c-11eb-8b24-b3e533021175.png)

**Comment by samip5** [comment]
If I manually change the xml version to 5.0:
![image](https://user-images.githubusercontent.com/1703002/119085783-0d92d580-ba0d-11eb-8bee-9751d54ac147.png)

**Comment by mbdraks** [comment]
Got it, thanks for testing.

I'll consider maintaining a v5.0 version.

**Comment by IsraelXabregas** [comment]
> Got it, thanks for testing.
> 
> I'll consider maintaining a v5.0 version.

Have a update about that?

**Comment by mbdraks** [comment]
> > Got it, thanks for testing.
> > I'll consider maintaining a v5.0 version.
> 
> Have a update about that?

Yes. I have decided not to support Zabbix v5.0 at this point due to being unable to dedicate enough time to this project, if I support one additional version that would only take time that could best be spent adding new features. Moving forward I will plan to support the next LTS version.
